src/smooth.cpp, src/smooth.hpp
This will resolve #19. Testing now.
=> handle abPOA traceback failure by retrying with unbanded alignment

src/blocks.cpp, src/breaks.cpp, src/main.cpp, src/progress.hpp, src/smooth.cpp
This puts a progress meter where we were previously using locking to write to std::cerr.
=> Progress meter everywhere

CMakeLists.txt, src/cleanup.cpp, src/cleanup.hpp, src/main.cpp, src/prep.cpp
This implements -p Yn as a final graph sorting and cleanup step.
=> Cleanup final graph order

.github/workflows/small_test_on_push.yml
=> set nthreads=2

src/breaks.cpp, src/consensus_graph.cpp, src/consensus_graph.hpp, src/main.cpp, src/prep.cpp, src/progress.hpp, src/smooth.cpp, src/smooth.hpp
This PR introduces the new version of odgi, which leads to an increase in performance.
=> smoothxg's speeding up using fastified odgi

src/breaks.cpp
This PR tries to squeeze the blocks split speed a bit more.
=> smarterize the blocks split

src/consensus_graph.cpp
This fix avoid a segmentation fault with the following command:
```
smoothxg -g DRB1-3123.fa.gz.pggb-s10000-p70-n5-a70-K16-k19-w50000-j5000-e5000-I0-N.seqwish.gfa.prep.gfa -o smoothxg.gfa -a -s cons -w 50000 -s 10000 -n -C 1000 -J 0.7 -M -I 0
```
```
...
[smoothxg::main] building xg index from smoothed graph
[smoothxg::create_consensus_graph] deriving consensus graph with consensus-jump-max=1000
[smoothxg::create_consensus_graph] finding consensus links
[smoothxg::create_consensus_graph] adding consensus paths
[smoothxg::create_consensus_graph] cleaning up redundant link paths
[smoothxg::create_consensus_graph] removing edges connecting the path with a gap less than consensus-jump-max=1000
[smoothxg::create_consensus_graph] trimming back link paths
[smoothxg::create_consensus_graph] final …
```
=> fix edge case which leads to segmentation fault

README.md
Update the README to reflect that we need at least GCC V10.1.
=> we need at least GCC V10.1

src/smooth.cpp
Now, by default, we will pick the orientation of a POA block based on the relative orientation of the path in it with the lowest rank (path handle) in the input graph.
The input graph order is defined by the order in the FASTA. In seqwish, this tends to structure the graph sort and dominant layout, and it's consistent to preserve this behavior here.
=> groom the POA block graphs using the paths based on their order in the input

src/prep.cpp
A bit more information can be useful for debugging (as in this case https://github.com/pangenome/pggb/issues/57).
=> show progess for the `gfa_to_handle` function

.github/workflows/small_test_on_push.yml, CMakeLists.txt, src/smooth.cpp, src/smooth.hpp, src/zstdutil.cpp, src/zstdutil.hpp
Compress block graphs in memory by serializing them to a string and compressing it with zstd.
=> Zip graphs

README.md, src/blocks.cpp, src/blocks.hpp, src/breaks.cpp, src/consensus_graph.cpp, src/main.cpp, src/smooth.cpp
... to get our allele length in consensus graph generation.
=> use distances from consensus paths

src/consensus_graph.cpp
Perfect link paths between different consensi had been dropped. This led to fragmentation and a reduction in consensus graph quality. Also, some essential link paths that weren't perfectly unique (in a progressive sense) were dropped, causing disconnected components.
=> improve consensus 'tegrity

src/main.cpp
This resolves a boundary effect introduced in 30e9adcc53cb6a1f9ef010bfd198445c25c626ab.
The poa-max parameter began to have two roles. 1) provide a target length for the POA problem, 2) provide an absolute max POA length. It's better for the target to be half of our max limit. Default parameters are adjusted.
=> Weird splits

src/main.cpp
The embedding can be disabled with `-V, --vanish-consensus`.
=> always include the consensus paths even without MAF or consensus graphs

src/smooth.cpp
Instead of aligning twice, we can just align once in the orientation suggested by the graph itself.
=> respect the graph strand when running abPOA

.gitmodules, CMakeLists.txt, src/smooth.cpp, src/smooth.hpp
This builds but breaks immediately with out-of-bounds memory access. Investigating.
=> abPOA v1.2.4

src/smooth.cpp
And update odgi (for pggb use).
=> Wider POA band

src/main.cpp, src/smooth.cpp
=> Even wider band

src/main.cpp, src/smooth.cpp, src/smooth.hpp
This lets us limit memory usage during this step.
=> specifically set the number of POA threads

src/main.cpp
So we don't have to prevent it. yay
=> abpoa local mode is good now

README.md
The smoothxg's bioconda recipe is coming https://github.com/bioconda/bioconda-recipes/pull/29778.
=> BIOCONDA and GUIX in the README

src/smooth.cpp
Working to understand if the super big bandwidth has any marginal benefit over a slightly smaller one.
=> reduce bandwidth

CMakeLists.txt
Related to https://github.com/pangenome/pggb/issues/150
=> Fix version generation

src/cleanup.cpp, src/prep.cpp
We want to propagate the reference-based grooming and reference-based PG-SGD to PGGB.
=> update odgi to rPG-SGD

src/main.cpp
This fixes https://github.com/pangenome/smoothxg/pull/174#issuecomment-1311608084.
=> fix wrong file path issue

src/main.cpp, src/smooth.cpp, src/smooth.hpp
This helps for debugging purposes.
=> allow writing FASTAs of only hard blocks;

src/progress.hpp
To avoid huge log files like in https://github.com/pangenome/pggb/issues/298.
=> Less verbose logging
