pangenome/smoothxg

.gitmodules, CMakeLists.txt, src/blocks.cpp, src/breaks.cpp, src/breaks.hpp, src/main.cpp, src/smooth.cpp
With this commit, we cut blocks where we would have more than a maximum amount of sequence from any given input.
The cutting is guided by inference of VNTRs when they are present, and if a VNTR is found, the cut length is set to 1/2 the mean length of the repeat we find (considering repeats found in all sequences).
This ensures that we don't accidentally end up with too much sequence in spoa, which can easily exhaust memory.
=> Cut blocks to prevent out of memory in POA

src/blocks.cpp, src/blocks.hpp, src/breaks.cpp, src/breaks.hpp, src/main.cpp, src/smooth.cpp
Paths were always sorted from shortest to longest, leading to bad results applying `SPOA`:
```
abpoa -s -r 3 DRB1-3123.fa.gz > DRB1-3123.abpoa-s.gfa
master/smoothxg -g DRB1-3123.abpoa-s.gfa -t 16 -w 1000000 -l 1000000 -e 10000000 -j 10000000 > x.gfa  && odgi build -g x.gfa -o x.og -s &&  odgi layout -i x.og -o x.lay -t 16 -P && odgi draw -i x.og -c x.lay -p x.png
```
With this PR:
- when `SPOA` is applied for smoothing blocks, the paths are sorted from the longest to the shortest.
```
smoothxg -g DRB1-3123.abpoa-s.gfa -t 16 -w 1000000 -l 1000000 -e 10000000 -j 10000000 > x.gfa  && odgi build -g x.gfa -o x.og -s &&  odgi layout -i x.og -o x.lay -t 16 -P && odgi draw -i x.og -c x.lay -p x.png
```
- when `abPOA` is applied for smoothing blocks, the paths are sorted from the shortest to the …
=> fixed how sort the paths by length

src/smooth.cpp
This updates the transition of abPOA graph to odgi graph as fixed in @yangao07's https://github.com/yangao07/abPOA/commit/865e7285fac162e0b83eff83615782461894bc1d.
=> bugfix when traversing abPOA graph

src/blocks.cpp
We shouldn't have lots of empty blocks. It's just confusing. Erasing them is easy and only helps.
=> Erase empty blocks

README.md, src/blocks.cpp, src/blocks.hpp, src/breaks.cpp, src/main.cpp, src/smooth.cpp, src/smooth.hpp
This integrates abPOA.
We use global mode except for broken blocks, where it appears that local mode is preferable due to the incomplete matching between path fragments overlapping the block.
Global and local mode are selectable, but the defaults are reversed for spoa and abPOA.
=> No limit abpoa

CMakeLists.txt, src/blocks.hpp, src/maf.hpp, src/main.cpp, src/smooth.cpp, src/smooth.hpp
This makes it possible, using the `-m` option, to output a MAF file with the MSAs obtained during the smoothing (`-m/--max-copy-length` becames `-W`).
**Little example (small.gfa)**
```
H	VN:Z:1.0
S	1	CAAATAAG
S	2	A
S	3	GCT
S	4	T
L	1	+	2	+	0M
L	2	+	3	+	0M
L	2	+	4	+	0M
P	x	1+,2+,3+	*
P	y	1+,2+,4+	*
```
Applying abPOA in global alignment mode:
```
smoothxg -g small.gfa -n -m out.maf && cat out.maf
##maf version=1
a block=0 loops=false
s y 0 10 + 10 CAAATAAGA--T
s x 0 12 + 12 CAAATAAGAGCT
```
Applying SPOA in local alignment mode with a little `max_block_weight` and adding the consensus sequences:
```
smoothxg -g small.gfa -n -m out.maf -S -w 3 -a && cat out.maf
##maf version=1
a block=0 loops=false
s x 0 9 + 12 CAAATAAGA
s y 0 9 + 10 CAAATAAGA
s Consensus_0 0 9 + 9 CAAATAAGA
a block=1 …
```
=> maf output and merged-consensus sequences embedding in the smoothed graph

src/smooth.cpp
This avoids the creation of graphs that have paths traversing non-existent edges by adding all edges in every path to the graph.
This isn't the best solution, because we're doing extra work. It might even make sense to remove the other edge additions in the lacing.
=> force embedding of paths

src/smooth.cpp
Every string and vector is explicitly cleaned up.
=> fix memory consumption during MAF output creation

src/main.cpp
=> now the prep.gfa is not removed anymore when specifying -K

src/main.cpp
This fixes a bug introduced in #25 which resulted in losing GFA input when using `-n`. In addition, the temporary file (the sorted input when `-n` is not specified) is put in the existing directory specified by `-b`, fix that could close the #18.
=> fix keep input gfa and directory for temporary files

src/maf.hpp, src/smooth.cpp
This fixes a bug that led to double consensus in some merged blocks in the MAF output. In addittion, together with PR #26, it improves memory consumption when the merged consensus are added in the smoothed graph and/or the MAF output is generated.
Before these last fixes, testing on a yeast pangenome, the additional memory required for generating the MAF output was ~1.3GB, now ~250/300 Mb.
=> improve MAF output memory consumption and fix merged consensus

src/blocks.hpp, src/breaks.cpp, src/breaks.hpp, src/main.cpp, src/smooth.cpp, src/smooth.hpp
This PR does several things.
First, it lets us split blocks into "big" sequences and "shorter" sequences less than some threshold of the maximum sequence length. This can avoid the occasional problem of aligning a really short sequence into a long POA. The set of short sequences are all still aligned to each other in another (subsequently placed) block.
It also adjusts the abPOA implementation to not break when our traceback fails, but rather to return a flag that we can handle. It's currently not handled, which could be dangerous :boom: . But, testing hasn't shown any issues yet.
=> Split blocks, trace back ok

src/smooth.cpp
Fixed a bug in the MAF blocks merge for reversed stranded sequences.
=> fixed how a reversed sequences are merged

src/smooth.cpp
This relaxes the constraints to merge the MAF blocks and the consensus sequences embedded in the smoothed graph, leading to bigger merged groups. The consensus graph generation in #32 could take advantage of longer consensus sequences.
**Before**
```
##maf version=1
a blocks=0-4 loops=false merged=true
s x              0 47 + 58 CAAATAAGGCTCTTGGAAATTTTCTGGAGATTACAATATGCATCTCA
s y              0 44 + 44 CAAATAAGGCTC---GAAATTTTCTGGAGATTACAATATGCATCTCA
s Consensus_0    0 12 + 12 CAAATAAGGCTC-----------------------------------
s Consensus_1    0  4 +  4 ------------TTGG-------------------------------
s Consensus_2    0 12 + 12 ----------------AAATTTTCTGGA-------------------
s Consensus_3    0  7 +  7 ----------------------------GATTACA------------
s Consensus_4    0 12 + 12 …
```
=> merge more MAF blocks and consensus sequences

src/main.cpp, src/smooth.cpp, src/smooth.hpp
Now the MAF blocks / consensus sequences merge is disable by default.
Specifying the `-M/--merge-blocks` flag, a gentle merge mode is enabled: to be merged, a new block has to have all its paths contiguous to the paths in the group of the already merged blocks.
Such a behaviour can be modulated with the `-J/--contiguous-path-jaccard` options (`1.0` by default). Lower values correspond to more aggressive merge modes.
Little example
**example.gfa**
```
H	VN:Z:1.0
S	1	CAAATAAG
S	2	A
S	3	GCT
S	4	T
S	5	C
S	6	TTG
S	7	A
S	8	G
S	9	AAATTTTCTGGA
P	x	1+,3+,5+	*
P	y	1+,3+,4+,6+,8+,9+	*
P	z	2+,3+,5+,9+	*
```
**contiguous-path-jaccard 1.0 (gentle merge)**
```
smoothxg -M -F 1.0 -g example.gfa -m example.F_1.maf -n -a -w 3 > smooth.F_1.gfa
cat example.F_1.maf
```
```
##maf version=1
a blocks=0-1 …
```
=> better control over the merge behavior of MAF blocks and consensus sequences

src/consensus_graph.cpp, src/consensus_graph.hpp, src/main.cpp
The path step iteration is just so much faster in XG. Consensus graphs appear to be correct.
=> use XG index for consensus graph generation

src/breaks.cpp
Breaking these doesn't matter, and it results in *crazy* structures in the graph that are just arbitrary misalignments of the single sequence.
(There are still issues with broken blocks / repeat blocks to be solved with a change to the POA algorithm.)
=> don't break when there's only one sequence in the block

.gitmodules, CMakeLists.txt, src/breaks.cpp, src/breaks.hpp, src/consensus_graph.cpp, src/main.cpp, src/smooth.cpp
Require all sequences going into a single POA problem to be connected by edit-based identities of at least `-I[N], --block-id-min=[N]`.
This mitigates spurious long-range or mid-SV alignments, and lets us define a bound for the relationship based on the pairwise distances between the sequences. A graph with higher `--block-id-min` will be more "unfolded" and also "smoother" but this can increase graph size.
=> Cluster POA using spanning minimum identity

src/breaks.cpp
This should fix out of memory errors in the block splitting step.
=> free the edlib alignment result

src/blocks.cpp, src/blocks.hpp, src/breaks.cpp, src/breaks.hpp, src/main.cpp, src/smooth.cpp, src/smooth.hpp
This introduces several changes to minimize the memory consumption by removing unused fields, using a bitvector during the blocks' preparation, and to avoid storing information (vectors) neeeded only during specific steps before the POA phase. Refactoring the code, the blocks' preparation should be slighlty faster too.
Moreover, now the blocks are read/written on/from disk, exploiting a memory-mapped multimap, and avoiding to keep everything in memory.
**Yeast dataset (`-w 100` to have much more blocks, 759398 in particular)**
```
odgi stats -i Sc+Sp.pan.fpal10k.Y.G50.og -S
#length	nodes	edges	paths
19830938	4712138	6513053	192
```
```
.../master/smoothxg -g Sc+Sp.pan.fpal10k.Y.G50.gfa -o smooth.gfa -t 16 -I 0 -n -w 100
Elapsed (wall clock) time (h:mm:ss or m:ss): 7:29.46
Maximum resident …
```
=> read/write POA blocks on disk, code refactoring and bug fixing

src/breaks.cpp
Currently, the block splitting takes the majority of the time to smooth an input graph (also ~90-95% of the total).
In this PR, the clustering is applied only on unique sequences.
**Mouse pangenome (chr19)**
```
#length	nodes	edges	paths
89882247	2605372	4229034	3144
```
```
../master/smoothxg -t 16 -g mouse_pangenome.chr19.gfa -w 20000 -l 0 -e 100 -j 100 -o mouse_pangenome.chr19.smooth.gfa
```
```
[smoothxg::main] smoothed graph length 56082702bp in 13633833 nodes
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:08:05
Maximum resident set size (kbytes): 15920644
```
```
../branch/smoothxg -t 16 -g mouse_pangenome.chr19.gfa -w 20000 -l 0 -e 100 -j 100 -o mouse_pangenome.chr19.smooth.gfa
```
```
[smoothxg::main] smoothed graph length 55722586bp in 13462793 nodes
...
Elapsed (wall clock) …
```
=> speed up the blocks splitting

CMakeLists.txt, src/blocks.cpp, src/blocks.hpp, src/breaks.cpp, src/consensus_graph.cpp, src/main.cpp, src/progress.hpp, src/smooth.cpp, src/xg.cpp
The worst was in the progress_meter, but this should improve things in many parts, including xg and the blockset_t.
The consensus graph generation had a stack overflow that we can avoid by allocating the mmmultimap on the heap. Further improvements could be based on factoring the run-on function into a lot of smaller pieces.
=> massive cleanup of memory problems

src/blocks.cpp, src/blocks.hpp, src/breaks.cpp
In this way, the blocks take up ~23% less space on disk (and memory), as expected.
**cerevisiae.pan.fa.gz.pggb-s50000-p90-n5-a70-K16-k71-w30000-j5000-e5000.sY.G30.gfa**
```
-rw-rw-r-- 1 guarracino guarracino  17M gen 12 19:02 blocks.broken.temp_master
-rw-rw-r-- 1 guarracino guarracino  13M gen 12 19:02 blocks.broken.temp_branch
```
**Sc+Sp.pan.fpal10k.Y.G50.gfa**
```
-rw-rw-r-- 1 guarracino guarracino 307M gen 12 19:07 blocks.broken.temp_master
-rw-rw-r-- 1 guarracino guarracino 239M gen 12 19:05 blocks.broken.temp_branch
```
=> simplify the block structure, saving 16 byte for each path_range

src/smooth.cpp, src/smooth.hpp
This removes unnecessary steps and memory allocations. However, dangerous memory peaks are still observed with abPOA. Going deeper to catch the problem.
=> refactoring abPOA integration (and cleaning the SPOA one)

src/maf.hpp, src/smooth.cpp, src/smooth.hpp
This generalize the block merge, managing tricky cases with blocks which presents loop.
**LPA dataset**
```smoothxg -t 16 -g LPA.prep.gfa -a -w 5000 -m smooth.maf -M -J 0 -n -o smooth.gfa```
Master: 26 blocks
Branch: 5 blocks
```smoothxg -t 16 -g LPA.prep.gfa -a -w 5000 -m smooth.maf -M -J 0.5 -n -o smooth.gfa```
Master: 228 blocks
Branch: 97 blocks
```smoothxg -t 16 -g LPA.prep.gfa -a -w 5000 -m smooth.maf -M -J 1 -n -o smooth.gfa```
Master: 283 blocks
Branch: 139 blocks
=> unleash the merge with loops and flipping blocks

CMakeLists.txt, src/blocks.hpp, src/breaks.cpp, src/main.cpp, src/tempfile.cpp, src/tempfile.hpp, src/xg.cpp, src/xg.hpp
This avoid conflicts when multiple instances of smoothxg are run in parallel.
=> temporary filenames management for xg and blockset

src/consensus_graph.cpp, src/main.cpp
This allows the user to specify a set of reference paths that should be embedded in the output consensus graphs.
These can be included with, or replace the consensus paths generated in the MSA step.
=> embed reference sequences in consensus graph

src/maf.hpp, src/main.cpp, src/smooth.cpp, src/smooth.hpp
This PR generalizes the block merge, no longer requiring the blocks to be contiguous for merging. This reduces the number of resulting total blocks in the MAF file and the number of total consensus sequences in the smoothed graph. Less, and therefore longer, consensus sequences lead also to more grained consensus graphs, with bigger nodes which are tastier for aligners as GraphAligner.
=> removal of the contiguity constraint in merging blocks

src/consensus_graph.cpp
This would have resulted in path corruption with multiple overlapping reference paths.
=> fix apparent bug with consensus embedding

src/main.cpp
The current POA parameters are a bit too permissive in opening gaps, leading to graphs with too many nodes. Increasing the gap opening penalties lead to longer smoothed graphs, but with less nodes. Moreover, this prevents having too many opened gaps which lead to an "indel explosion" when calling variants in the tricky regions.
Unfortunately, this comes with a price, increasing time and memory consumption because the PO graphs tends to be longer.
**[HPRCy1.MHC dataset](https://github.com/pangenome/MHC)**
The current default parameters for abPOA are in the first row.
In the unsmoothed graph, 20726 SNPs and 44584 INDELs are identified with gfautil.
| --poa-params  | smoothed graph length (bp) | smoothed graph nodes | consensus_graphs@1000 nodes | consensus_graphs@1000 length (bp) | time …
=> less permissive gap openings during the POA step

.github/workflows/small_test_on_push.yml, CMakeLists.txt, README.md
This provides a dramatic reduction in memory usage, particularly in the abPOA step, where we experience a lot of memory fragmentation.
=> use jemalloc

src/blocks.cpp
This just causes overhead spawning / killing threads.
=> no need to spawn threads to disjoint set each block

src/consensus_graph.cpp, src/consensus_graph.hpp
This helps to avoid the introduction of tips into the consensus graph. We collect link paths based on the consensus path end they're on, not the consensus path itself. The first and last 1/8th of each consensus path is considered beginning and end. The rest is the middle.
=> link consensus parts rather than full paths

CMakeLists.txt, src/blocks.cpp, src/blocks.hpp
Updating `odgi` so we won't have to use `-mcx16` during compilation anymore.
=> replacing dset64-gccAtomic.hpp with dset64.hpp

src/smooth.cpp
This is allows us to run faster and use lower-memory than the full abPOA approach.
=> enable abPOA seeding

src/smooth.cpp
To avoid alignment errors, we must use large windows (for alignment) during seeded abPOA.
=> specify conservative seeding parameters

src/main.cpp
This works _much_ better than global mode, and avoids the "accordion" patterns which occur with global mode. However, it is slower and we have to use a smaller POA target length in pggb.
=> local alignment by default

src/main.cpp, src/smooth.cpp
This makes sure we have a large fixed overlap, and drops the fractional requirement low.
=> Large fixed POA min overlap

.gitmodules, CMakeLists.txt, README.md, src/breaks.cpp, src/breaks.hpp, src/cleanup.cpp, src/main.cpp, src/prep.cpp, src/smooth.cpp, src/smooth.hpp
On the first tests on human data, performing SPOA only on unique sequences gives runtime improvements of roughly one order of magnitude.
Block statistics are written in a TSV file when `smoothxg` is built by specifying `-DPOA_DEBUG=ON` in `cmake`.
Missing features:
=> Perform the POA on unique sequences + Emit POA blocks information in a table

CMakeLists.txt, scripts/generate_git_version.sh
Same as https://github.com/pangenome/odgi/pull/482.
Docker/Singularity images of PGGB display the wrong version of `odgi`. The `odgi` binary is correct, only the version it shows is wrong. In PGGB we use the `odgi` compiled with `smoothxg` and there the script to catch `odgi`'s version wrongly calls `smoothgx`'s git, not `odgi`'s.
=> Fix versioning

src/smooth.cpp
SPOA and abPOA introduce links not supported by any path, leading to graphs with uncovered edges (see https://github.com/pangenome/pggb/issues/299). This PR avoids that and should fix https://github.com/pangenome/pggb/issues/299. Moreover, it adds a tiny optimization in case there are no blocks to flip.
=> Fix uncovered edges

src/main.cpp
If the last path only had 1 fragment, it was lost along the way. This PR solves this problem found here https://github.com/pangenome/pggb/issues/377. Furthermore, we now also check that the number of paths in the input graph and the smoothed graph are the same.
=> Fix path embedding

src/main.cpp
Should fix #210, where the `smoothxg::prep` would load in the original graph for every iteration, rather than using the output of the previous iteration (the _path_input_gfa_). This only affected graph prep, so the behaviour was likely always correct when `--no-prep`.
=> Fix: use output of previous smoothing iteration as input for next
